service: commentative-api

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-west-1
  profile: voting
  environment:
    COMMENTATIVE_TABLE: "${self:service}-${opt:stage, self:provider.stage}-db"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.COMMENTATIVE_TABLE}"

functions:
  commentativePost:
    handler: action/post.main
    events:
      - http:
          path: commentative
          method: post
  commentativeGet:
    handler: action/get.main
    events:
      - http:
          path: commentative/{uuid}
          method: get

resources:
  Resources:
    MatchesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.COMMENTATIVE_TABLE}
